source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'shotgun'
gem 'faker', require: 'faker'
gem 'pry'
gem 'minitest'
gem 'capybara'
gem 'launchy'
gem 'sequel'
gem 'sqlite3'
gem 'byebug'